CC = gcc
CFLAGS = -Wall -lpthread -lm

default: all

all: primos1 primos4 primos8 primos16 primos128 primos264


primos1: primos1.c
	$(CC) primos1.c $(CFLAGS) -o primos1

primos4: primos4.c
	$(CC) primos4.c $(CFLAGS) -o primos4

primos8: primos8.c
	$(CC) primos8.c $(CFLAGS) -o primos8

primos16: primos16.c
	$(CC) primos16.c $(CFLAGS) -o primos16

primos128: primos128.c
	$(CC) primos128.c $(CFLAGS) -o primos128

primos264: primos264.c
	$(CC) primos264.c $(CFLAGS) -o primos264